spring:
  application:
    name : finance-tracker-backend
  datasource:
    url:  jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:finance-tracker}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true




